<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.9.2
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
$entityType = $this->getProductTypeId();
$attributeSetCollection = $this->setEntityType($entityType);

     foreach ( $attributeSetCollection as $attributeSet ) {
    $attributeSetId = $attributeSet->getAttributeSetId ();
    $product = Mage::getSingleton ( "catalog/product" )->setTypeId ( 'configurable' )->setAttributeSetId ( $attributeSetId );
    $attributes = $product->getTypeInstance ( true )->getSetAttributes ( $product );
    $attributeFlag = 0;
    foreach ( $attributes as $attribute ) {
        $attributeDetails = Mage::getSingleton ( "eav/config" )->getAttribute ( "catalog_product", $attribute->getAttributeCode () );
        $options = $attributeDetails->getSource ()->getAllOptions ( false );
        foreach ( $options as $option ) {
            echo '<br/>' . $option ["label"] . '';
        }
        if (count ( $options ) < 1) {
            echo '<br/>' . $this->__ ( 'No option available for' ) . ' "' . $attribute->getName () . '".';
        }
    }
}
?>