<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.9.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
/** 
 * @var $this Mage_Catalog_Block_Product_List 
 */
?>

<?php
  $timerColor = Mage::getStoreConfig('superdeals/timer/text');
$saveDisLableColor = Mage::getStoreConfig('superdeals/timer/save_dis_lable_color');
$saveDisPriceColor = Mage::getStoreConfig('superdeals/timer/save_dis_price_color');
$saveCatTimeFontSize = Mage::getStoreConfig('superdeals/timer/save_cat_time_font_size');
?>
                                
                                <style type="text/css">
        /* design for Category page */
        .deal-price-box .price-label {color: #<?php echo $saveDisLableColor ?>; }
        .deal-price-box .price {color: #<?php echo $saveDisPriceColor ?>; }
        .dealtimer_listpage .dealtimer_listpage_timer span, .dealtimer_listpage .dealtimer_listpage_timer{ color: #<?php echo $timerColor ?>; font-size:<?php echo $saveCatTimeFontSize ?>px; }
    </style>
    <?php 
/**
 * Get Customer Details
 */
$customer = Mage::getSingleton('customer/session')->getCustomer();
/**
 * Get Wishlist
 */
$wishListDatas = Mage::getSingleton('wishlist/wishlist')->loadByCustomer($customer);
/**
 * Get Item Collection
 */
$wishListItemCollection = $wishListDatas->getItemCollection();
$arrProductIds = array();
/**
 * Check the wish list item collection has values
 */
if (count($wishListItemCollection)) {
foreach ($wishListItemCollection as $item) {
$product = $item->getProduct();
$arrProductIds[] = $product->getId();
}
}

?>
<?php
/** 
 * Load Product Collection
 */
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    
    if (!Mage::registry('timer_count')) {
        $count = 1;
        Mage::register('timer_count', $count);
    } else {
        $count = Mage::registry('timer_count');
        $count = $count + 1;
        Mage::unregister('timer_count');
        Mage::register('timer_count', $count);
    }
    
    
?>
<?php 
/**
 * Check the product collection count is not defined already
 * if so display message like there are no products matching the selection
 */
if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php 
    /**
     *  List mode 
     */
     ?>
    <?php 
    /**
     * 
     * check the mode is not equal to 'grid'
     */
    if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php 
        ++$_iterator;
        if( $_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" 
            title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                <?php 
                /** Based on the native RWD styling, 
                 * product images are displayed at a max of ~400px wide 
                 * when viewed on a one column page layout with four product columns from a 1280px viewport. 
                 * For bandwidth reasons, we are going to serve a 300px image, 
                 * as it will look fine at 400px and most of the times, 
                 * the image will be displayed at a smaller size (eg, if two column are being used or viewport is smaller than 1280px).
                 * This $_imgSize value could even be decreased further,
                 * based on the page layout (one column, two column, three column) and number of product columns. 
                  */ ?>
                <?php $_imgSize = 300; ?>
                <?php 
                /**
                 * get Product Id
                 */
                ?>
                <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                     src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize($_imgSize); ?>"
                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
            </a>
            <?php 
            /**
             * Product description 
             */
            ?>
            <div class="product-shop">
                <div class="f-fix">
                    <div class="product-primary">
                    <?php 
                    /**
                     * Get Product Name
                     */?>
                        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" 
                        title="<?php echo $_productNameStripped; ?>">
                        <?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                       <?php 
                       /**
                        * Get Rating Summary
                        */?>
                        <?php if($_product->getRatingSummary()): ?>
                        <?php /**
                              Get Review Summary
                                */?>
                        
                        <?php echo $this->getReviewsSummaryHtml($_product) ?>
                        <?php endif; ?>

                        <?php
                            $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                            foreach($_nameAfterChildren as $_nameAfterChildName):
                                $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                $_nameAfterChild->setProduct($_product);
                        ?>
                            <?php echo $_nameAfterChild->toHtml(); ?>
                        <?php endforeach; ?>
                    </div>
                    <div class="product-secondary">
                    <?php 
                    /**
                     * Get Price Html
                     */
                    ?>
                        <?php echo $this->getPriceHtml($_product, true) ?>
                    </div>
                   <?php 
                   
                   if(strtotime($_product->getSpecialToDate())>=strtotime("now")){
                   
                    ?>
                     <div class="dealtimer_listpage">
                                                        <div id="countbox<?php echo $count; ?>"
                                                             class="dealtimer_listpage_timer">
                                                       </div>
                      </div>
                      
                       <script type="text/javascript">
                                        var dthen<?php echo $count; ?> = new Date("<?php echo Date("m/d/y", strtotime($_product->getSpecialToDate())) . ' 11:59:00 PM'; ?>");
                                        start = "<?php echo Date("m/d/y h:i:s A", strtotime(Mage::app()->getLocale()->date(null, null, "en_US", true))); ?>";
                                        startDate = Date.parse(start);
                                        var dnow<?php echo $count; ?> = new Date(startDate);
                                        if (CountStepper > 0)
                                            ddiff = new Date((dnow<?php echo $count; ?>) - (dthen<?php echo $count; ?>));
                                        else
                                            ddiff = new Date((dthen<?php echo $count; ?>) - (dnow<?php 
                            echo $count; ?>));
                                        gsecs<?php echo $count; ?> = Math.floor(ddiff.valueOf() / 1000);
                                        var iid<?php echo $count; ?> = "countbox<?php 
                                        echo $count; ?>";
                                        CountBack(gsecs<?php echo $count; ?>, iid<?php
                                         echo $count; ?>, <?php echo $count; ?>);
                                        j++;
                                            </script>
                        <?php $count = $count + 1; ?>
                    <?php }?>
                    
                    
                    <div class="desc std">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" 
                        title="<?php echo $_productNameStripped ?>" class="link-learn">
                        <?php echo $this->__('Learn More') ?></a>
                    </div>
                    <div class="product-secondary">
                        <?php if($_product->isSaleable() && !$_product->canConfigure()): ?>
                            <p class="action"><button type="button" 
                            title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" 
                            onclick="setLocation('<?php echo Mage::helper('checkout/cart')->getAddUrl($_product) ?>')">
                            <span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                        <?php elseif($_product->isSaleable()): ?>
                            <p class="action"><a title="<?php echo $this->__('View Details') ?>" class="button" 
                            href="<?php echo $_product->getProductUrl() ?>">
                            <?php echo $this->__('View Details') ?></a></p>
                        <?php else: ?>
                            <p class="action availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                        <ul class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <?php if(in_array($_product->getId(),$arrProductIds)){
                            $class =  'added'; 
                            }
                            else{ $class = ''; } ?>
                                <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" 
                                title="<?php echo $this->__('Add to Wishlist') ?>" 
                                class="link-wishlist <?php echo $class; ?>">
                                <?php echo $this->__('Add to Wishlist') ?></a></li>
                            <?php endif; ?>
                            <?php if($addtocompareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <li><a href="<?php echo $addtocompareUrl ?>" class="link-compare">
                                <?php echo $this->__('Add to Compare') ?></a></li>
                            <?php endif; ?>
                        </ul>
                    </div>
                </div>
            </div>
        </li>
 <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>
  
<?php 
/**
 * Product Collection
 */
?>
    <?php $_collectionSize = $_productCollection->count() ?>
<?php 
/**
 * Get Count 
 */

?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col">
        <?php $i=0; 
        foreach ($_productCollection as $_product): ?>
            <li class="item<?php if(($i-1)%$_columnCount==0){ ?> first
            <?php }
            else{ 
                  if($i%$_columnCount==0){ ?>
             last<?php }
                  } ?>">
               <?php 
               /**
                * Get Product Url
                */?>
                  
                <a href="<?php echo $_product->getProductUrl() ?>" 
                title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                    <?php $_imgSize = 210; ?>
                    <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                         src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                         alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                </a>
                <div class="product-info">
                    <h2 class="product-name">
                    <a href="<?php echo $_product->getProductUrl(); ?>">
                       <?php
                       echo $_product->getName();                     
                        ?>
                     </a>
                     </h2>

                    <?php
                        $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                        foreach($_nameAfterChildren as $_nameAfterChildName):
                            $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                            $_nameAfterChild->setProduct($_product);
                    ?>
                        <?php echo $_nameAfterChild->toHtml(); ?>
                    <?php endforeach; ?>
  <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    <?php endif; ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                   <?php  
    if (!Mage::registry('timer_count')) {
        $count = 1;
        Mage::register('timer_count', $count);
    } else {
        $count = Mage::registry('timer_count');
        $count = $count + 1;
        Mage::unregister('timer_count');
        Mage::register('timer_count', $count);
    }
         ?>           
                    <?php  if(strtotime($_product->getSpecialToDate())>=strtotime("now")){?>
                      <div class="dealtimer_listpage">
                                                        <div id="countbox<?php echo $count; ?>"
                                                             class="dealtimer_listpage_timer">
                                                       </div>
                      </div>
                      
                      
                        <script type="text/javascript">
                                        var dthen<?php echo $count; ?> = new Date("<?php echo Date("m/d/y", strtotime($_product->getSpecialTODate())) . ' 11:59:00 PM'; ?>");
                                        start = "<?php echo Date("m/d/y h:i:s A", strtotime(Mage::app()->getLocale()->date(null, null, "en_US", true))); ?>";
                                        startDate = Date.parse(start);
                                        var dnow<?php echo $count; ?> = new Date(startDate);
                                        if (CountStepper > 0)
                                            ddiff = new Date((dnow<?php echo $count; ?>) - (dthen<?php echo $count; ?>));
                                        else
                                            ddiff = new Date((dthen<?php echo $count; ?>) - (dnow<?php 
                            echo $count; ?>));
                                        gsecs<?php echo $count; ?> = Math.floor(ddiff.valueOf() / 1000);
                                        var iid<?php echo $count; ?> = "countbox<?php 
                                        echo $count; ?>";
                                        CountBack(gsecs<?php echo $count; ?>, iid<?php
                                         echo $count; ?>, <?php echo $count; ?>);
                                        j++;
                                            </script>
                        <?php $count = $count + 1; ?>
                        <?php }?>
                    <div class="actions">
                    
                    <?php if($_product->isSaleable() && !$_product->canConfigure()): ?>
                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart animated fadeIn" 
                            onclick="setLocation('<?php echo Mage::helper('checkout/cart')->getAddUrl($_product) ?>')">
                            <span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                        <?php elseif($_product->isSaleable()): ?>
                            <a title="<?php echo $this->__('View Details') ?>" class="button animated fadeIn" 
                            href="<?php echo $_product->getProductUrl() ?>">
                            <?php echo $this->__('View Details') ?></a>
                        <?php else: ?>
                            <p class="availability out-of-stock animated fadeIn" 
                            title="<?php echo $this->__('Out of stock') ?>">
                            <span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                    
                    <ul class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <?php if(in_array($_product->getId(),$arrProductIds)){
                            $class =  'added'; 
                            }
                            else{ 
                            $class = ''; 
                            } ?>
                                <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" 
                                title="<?php echo $this->__('Add to Wishlist') ?>" 
                                class="link-wishlist <?php echo $class; ?> animated fadeIn">
                                <?php echo $this->__('Add to Wishlist') ?></a></li>
                            <?php endif; ?>
                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" 
                                title="<?php echo $this->__('Add to Compare') ?>" class="link-compare animated fadeIn">
                                <?php echo $this->__('Add to Compare') ?></a></li>
                            <?php endif; ?>
                        </ul>
                     <a class="button-action"><span class="plus"></span></a>
                    </div>
                    <?php 
                    /**
 * Quick view of the product
 * If quickview has been enabled in admin section show quick view
 */
if(Mage::getStoreConfig('quickview/general/enabled')){ 
?> 
<input type="hidden" name="appthaAjaxLoading" id="appthaAjaxLoading" value="<?php echo $this->getSkinUrl('facebox/loading.gif') ?>" />
<input type="hidden" name="appthaAjaxClose" id="appthaAjaxClose" value="<?php echo $this->getSkinUrl('facebox/closelabel.png') ?>" />
<a rel="facebox" href="<?php echo Mage::helper('quickview')->getQuickViewUrl($_product->getId());?>">
<span class="quickview"><span class="btn-quickview"><?php echo $this->__('Quick View')?></span></span>
</a>
<?php } ?>
                </div>
            </li>          
        <?php endforeach ?>
    </ul>
    <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php endif; ?>

<script type="text/javascript">
//quick view function pop up
		$jQno = jQuery.noConflict();
		$jQno(function() {
			  $jQno('a[rel*=facebox]').facebox();
		});
		</script>