<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.9.2
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<?php
$productId = $this->getRequest ()->getParam ( 'item' );
$orderId = $this->getRequest ()->getParam ( 'id' );

$sellerId = Mage::getSingleton ( 'customer/session' )->getId ();
    /**
     * Get Product Info
     * @var unknown
     */
        $getSellerDetails = $this->getSellerInformation($sellerId);
        $getProduct = $this->getProductInformation($productId);

        $getProductName = $getProduct->getName();
        $currencySymbol = Mage::app ()->getLocale ()->currency ( Mage::app ()->getStore ()->getCurrentCurrencyCode () )->getSymbol ();
        /**
         * Add the comment and save the order (last parameter will determine if comment will be sent to customer)
        */
        $order = $this->getOrderInformation($orderId);
$j = 0;
$attributeLabel = $attributeValue = "";
foreach($order->getAllItems() as $orderItem){
    if($orderItem->getProductId () == $productId){
        $orderPrice = $orderItem->getPrice () * $orderItem->getQtyOrdered ();
        $productQty = $orderItem->getQtyOrdered ();
        $productAmt = $orderItem->getPrice ();
        $orderPrice = $productAmt * $productQty;
        $productQty = round($orderItem->getQtyOrdered ());
        if($j == 0) {
            $options = $orderItem->getProductOptions();
            $customOptions = $options['attributes_info'];
            $productTypeId = $getProduct->getTypeID();
            if($productTypeId == 'configurable'){

                $attributeValue = $customOptions[0][value];
                $attributeLabel = $customOptions[0][label];
                $j++;
            }
        }
    }
}
echo $comment = 'The item "<b>'.$getProductName.'</b>" has been cancelled by '.$getSellerDetails->getFirstname();

