<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.9.2
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */

/**
 * Get order item.
 */

$orderItem = $this->getItem();

 if($orderItem->getQtyInvoiced() >=  $orderItem->getQtyOrdered()){
     echo $this->getLayout()->createBlock('marketplace/order_vieworder')->setRefundStatus($orderItem)->setTemplate('marketplace/order/vieworder_refund.phtml')->toHtml();
}else{
    echo $this->getLayout()->createBlock('marketplace/order_vieworder')->setCancelStatus($orderItem)->setTemplate('marketplace/order/vieworder_cancel.phtml')->toHtml();
} ?>