<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.9.2
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
/**
 * Get order details
 */
$item = $this->getRefundStatus();
/**
 * Get order id from the params.
 */
$orderId = $this->getRequest()->getParam('orderid');

/**
 * Get the customer session.
 */
$customerData = Mage::getSingleton('customer/session')->getCustomer();
$loggedInCustomerId = $customerData->getId();

$orderPrdouctIds = Mage::helper('marketplace/vieworder')->getOrderProductIds(Mage::getSingleton('customer/session')->getId(),$orderId);


$orderItem = $item;

   $itemProductId = $item->getProductId();
  if($orderItem->getQtyRefunded() >=  $orderItem->getQtyOrdered()){
            ?>
            <?php echo $this->__('Refunded'); ?>
          <?php
          }else{
/**
 * Check refund request status.
 */
                $status = Mage::getModel('marketplace/order')->getItemRequestStatus($orderItem->getProductId(),$orderId,$loggedInCustomerId,4);
                if($status == 1){
                echo $this->__('Refund Request Sent');
                }else{
                $statusRefund = Mage::getModel('marketplace/order')->getItemRequestStatus($orderItem->getProductId(),$orderId,$loggedInCustomerId,2);
                $statusCancel = Mage::getModel('marketplace/order')->getItemRequestStatus($orderItem->getProductId(),$orderId,$loggedInCustomerId,3);
                if($statusRefund == 1 || $statusCancel == 1){
                ?>
            <a onclick="return confirm('<?php echo $this->__('Are you sure want to send refund request?'); ?>');" href="<?php echo Mage::getUrl('marketplace/shipment/refund').'id/'.$orderId.'/item/'.$itemProductId; ?>"><?php echo $this->__('Refund Request'); ?></a>
            <?php  }
            }
          }
             ?>