<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.9.2
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<?php
/**
 * get seller id
 */
$id = $this->getRequest()->getParam('id');
$currentDate = Mage::getModel('core/date')->date('Y-m-d');
/**
 * display product collection
 */
$sellerPage = Mage::getModel('marketplace/sellerprofile')->collectprofile($id);
?>
<div class="clear"></div>
   <div class="all-product-wrapper">
   <h2  class="pdct_name home_pdt_name"><span><span><?php echo $this->__('All'); ?></span> <?php
    echo $this->__('Products'); ?></span></h2>
    <div id="loader-image" style="display: none;">
   <img src="<?php echo Mage::getBaseUrl('skin') . 'frontend/base/default/images/ajax-loader.gif' ?>" />
    </div>
    <ul id = "mp-product-list" class="products-grid product_snipt f-left">
        <?php
        $displayProduct = $this->getCollection ();
        $storeId = Mage::app ()->getStore ()->getId ();
        $configValueStockStatus = Mage::getStoreConfig ( 'cataloginventory/options/show_out_of_stock', $storeId );
        if ($configValueStockStatus == 0) {
            Mage::getSingleton ( 'cataloginventory/stock' )->addInStockFilterToCollection ( $displayProduct );
        }
        /**
         * Check the display product count is greater than zero
         */
        if (count($displayProduct) > 0){
            foreach ($displayProduct as $_product) {
            /**
            * get compare url of the product
            */
            $_compareUrl = Mage::helper('catalog/product_compare')->getAddUrl($_product);
            /**
             * count the words of the product name
             */
                $wordsCountCategory = strlen($_product->getName());
                ?>
                <?php
                $productData = Mage::helper ( 'marketplace/outofstock' )->getProductObject ( $_product->getId () );
                $isAssignedProduct = $productData->getIsAssignProduct ();
                if ($isAssignedProduct) {
                    $assignProductId = $productData->getAssignProductId ();
                    $productDetail = Mage::helper ( 'marketplace/outofstock' )->getProductObject ( $assignProductId );
                    $productSku = $productDetail->getSku ();
                    $productUrl = $productDetail->getProductUrl ();
                } else {
                    $productSku = $_product->getSku ();
                    $productUrl = $_product->getProductUrl ();
                }
                    ?>
            <?php if(!empty($productSku)){?>
                <li class="item">
                    <a href="<?php echo $productUrl; ?>">
                        <img class="product-image" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(250); ?>" alt="<?php
                         echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                    </a>
                    <?php
                    /**
                     * Display product name
                     */
                    ?>
                   <div class="product-info" style="min-height: 0px;">
                    <h2 class="product-name">



                        <a href="<?php echo $productUrl; ?>">
                            <?php
                                echo $_product->getName();
                             ?>
                        </a>

                    </h2>
                   <div class="price-box"> <span class="regular-price">
                        <span class="price">
                            <?php
                            /**
                             * Display Product Price
                             * Get the product price
                             * Get Prodcut special price
                             * Get deal expire date
                             */
                            $price = $_product->getPrice();
                            $splPrice = $_product->getSpecialPrice();
                            $dealExpireDate = $_product->getSpecialToDate();
                            /**
                             * Check the product special price is not equal to empty
                             * and deal expire date is not equal to empty
                             * and deal expire date is greater than or equal to current date
                             * if so get the original price
                             * Get the discount price
                             * Calculate the saving amount
                             * Calcualte the savings percentage
                             */
                            if (!empty($splPrice) && ($dealExpireDate != '') && ($dealExpireDate >= $currentDate)) {
                                $originalPrice = $_product->getPrice();
                                $discountPrice = $_product->getSpecialPrice();
                                $savings = $originalPrice - $discountPrice;
                                $savingsPercentage = round(($savings / $originalPrice) * 100, 0);?>

                                <p class="offer_price"><?php echo Mage::helper('core')->currency($splPrice, true, false); ?></p>

                              <p class="original_price"><?php  echo '<del>' . Mage::helper('core')->currency($price, true, false) . '</del>'; ?></p>

                               <p class="discount_price"> <?php echo '('.$savingsPercentage.'%'.')';?></p>
                 <?php            
                $timerColor = Mage::getStoreConfig('superdeals/timer/text');
                $saveDisLableColor = Mage::getStoreConfig('superdeals/timer/save_dis_lable_color');
                $saveDisPriceColor = Mage::getStoreConfig('superdeals/timer/save_dis_price_color');
                $saveCatTimeFontSize = Mage::getStoreConfig('superdeals/timer/save_cat_time_font_size');
                
                if (!Mage::registry('timer_count')) {
                    $count = 1;
                    Mage::register('timer_count', $count);
                } else {
                    $count = Mage::registry('timer_count');
                    $count = $count + 1;
                    Mage::unregister('timer_count');
                    Mage::register('timer_count', $count);
                }
                ?>
                <style type="text/css">
                        /* design for Category page */
                        .deal-price-box .price-label {color: #<?php echo $saveDisLableColor ?>; }
                        .deal-price-box .price {color: #<?php echo $saveDisPriceColor ?>; }
                        .dealtimer_listpage .dealtimer_listpage_timer span, .dealtimer_listpage .dealtimer_listpage_timer{ color: #<?php echo $timerColor ?>; font-size:<?php echo $saveCatTimeFontSize ?>px; }
                    </style>
                           <?php if(!empty($dealExpireDate)){?>
                                              <div class="dealtimer_listpage">
                                              <div id="countboxes<?php echo $count; ?>"
                                              class="dealtimer_listpage_timer">
                                              </div>
                                              </div>
                                              <script type="text/javascript">
                                              var dthen<?php echo $count; ?> = new Date("<?php echo Date("m/d/y", strtotime($dealExpireDate)) . ' 11:59:00 PM'; ?>");
                                                                                      start = "<?php echo Date("m/d/y h:i:s A", strtotime(Mage::app()->getLocale()->date(null, null, "en_US", true))); ?>";
                                                                                      startDate = Date.parse(start);
                                                                                      var dnow<?php echo $count; ?> = new Date(startDate);
                                                                                      if (CountStepper > 0)
                                                                                          ddiff = new Date((dnow<?php echo $count; ?>) - (dthen<?php echo $count; ?>));
                                                                                      else
                                                                                          ddiff = new Date((dthen<?php echo $count; ?>) - (dnow<?php echo $count; ?>));
                                                                                      gsecs<?php echo $count; ?> = Math.floor(ddiff.valueOf() / 1000);
                                                                                      var iid<?php echo $count; ?> = "countboxes<?php echo $count; ?>";
                                                                                      CountBack(gsecs<?php echo $count; ?>, iid<?php echo $count; ?>, <?php echo $count; ?>);
                                                                                      j++;
                                                                                          </script>
                                                                                          <?php $count = $count + 1; 
                                                }
                            ?>
                            
                            
                            
                            
                            
                            <?php } else { ?>
                              <p> <?php echo Mage::helper('core')->currency($price, true, false); ?></p>
                          <?php  }
                          /**
                           * Quick view of the product
                           * If quickview has been enabled in admin section show quick view
                           */
                          if(Mage::getStoreConfig('quickview/general/enabled')){ ?>
                          <input type="hidden" name="appthaAjaxLoading" id="appthaAjaxLoading" value="<?php echo $this->getSkinUrl('facebox/loading.gif') ?>" />
                          <input type="hidden" name="appthaAjaxClose" id="appthaAjaxClose" value="<?php echo $this->getSkinUrl('facebox/closelabel.png') ?>" />
                          <a rel="facebox" href="<?php echo Mage::helper('quickview')->getQuickViewUrl($_product->getId());?>">
<span class="quickview"><span class="btn-quickview"><?php echo $this->__('Quick View')?></span></span>
  </a>
                          <?php }
                            ?>
                        </span>
                    </span></div>
                    <?php
                            /**
                             * Display Add to cart,
                             * add to wishlist
                             * and Add to compare
                             */
                            ?>  <div class="actions">

                            <?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart animated fadeIn" onclick="setLocation('<?php
                         echo Mage::helper('checkout/cart')->getAddUrl($_product) ?>')">
                         <span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>

                    <ul class="add-to-links">
                              <li><a href="<?php echo Mage::helper('wishlist')->getAddUrl($_product) ?>" title="<?php
                               echo $this->__('Add to Wishlist') ?>" class="link-wishlist <?php
                                 ?> animated fadeIn"><?php
                                 echo $this->__('Add to Wishlist') ?></a></li>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare animated fadeIn" title="<?php
                             echo $this->__('Add to Compare') ?>"><?php
                              echo $this->__('Add to Compare') ?></a></li>
                        </ul>
                       <a class="button-action"><span class="plus"></span></a>
                    </div>
                    <?php echo $this->helper('marketplace/marketplace')->getLabel($_product);  ?>
              </div>
               </li>
               <?php }?>
               <?php ?>
                        <?php   }
                        echo $this->getPagerHtml();
                    } else {
                        echo '<li class="no_products_avail"><p>'.$this->__('There is no product available for this seller.').'</p></li>';
                    }    ?>
    </ul>
      </div>