<?php

/** @var Algolia_Algoliasearch_Helper_Config $config */
$config = Mage::helper('algoliasearch/config');

/** @var Mage_CatalogSearch_Helper_Data $catalogSearchHelper */
$catalogSearchHelper = $this->helper('catalogsearch');

//$placeholder = $this->__('Search for products, categories, ...');
$placeholder = $this->__('Search PickOH');

/** Render form with autocomplete input **/
if ($config->isDefaultSelector()): ?>
    <form id="search_mini_form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
        <div id="algolia-searchbox" class="pickoh-search">
            <!--<label for="search"><?php //echo $this->__('Search:') ?></label>-->
            <input id="search" type="text" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" class="algolia-search-input" autocomplete="off" spellcheck="false" autocorrect="off" autocapitalize="off" placeholder="<?php echo $placeholder; ?>" />
            <span class="clear-cross clear-query-autocomplete"><i class="fa fa-times" aria-hidden="true"></i></span>
            <span id="algolia-glass" class="magnifying-glass button"><i class="fa fa-search" aria-hidden="true"></i></span>
        </div>
    </form>
<?php endif; ?>