<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.9.2
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
/**
 *  Initilize product types
 */
    $productId = $this->getRequest()->getParam('id');
    $product = Mage::helper('marketplace/marketplace')->getProductInfo($productId);

                    /**
                     * Get the configurable atributes
                     */
    $getConfigurableAttributes = $product->getTypeInstance()->getConfigurableAttributesAsArray();
    $attributeValueForPriceArray = array();


    foreach($getConfigurableAttributes as $attribute){
    /**
     * check attribute code has been set for attribute
     */
    if (isset ( $attribute ['attribute_code'] )) {
        $attributeDetails = $this->getAttributeData ( $attribute ['attribute_code'] );
        $options = $attributeDetails->getSource ()->getAllOptions ( false );
        foreach ( $options as $option ) {
            /**
             * Initialising option value as empty
             */
            $optionValue = '';
            /**
             * Get the option value
             */
            $optionValue = $option ['value'];
            
            /**
             * Check attribute price value percent has been set
             */
            if (isset ( $attributeValueForPriceArray [$optionValue] ['is_percent'] ) && $attributeValueForPriceArray [$optionValue] ['is_percent'] == 1) {
                $attributeValueForPricePercent = $attributeValueForPriceArray [$optionValue] ['is_percent'];
                echo '%';
            }
        }
    }
}