<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.9.2
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
/**
 * Check the product custom options is equal to 1
 */
$select_sub_option_count = '';
$optionCount = $selectSubOptionCount = 0;
$option_count = '';

$option_count = 1;
$child_option_count_value = 1;
$select_sub_option_count = 0;

$o = $this->getDateInfo ();

$optionTitle = $optionTypeData = $optionIsRequire = $optionSortOrder = '';
$optionTitle = $o->getTitle ();
$optionTypeData = $o->getType ();
$optionIsRequire = $o->getIsRequire ();
$optionSortOrder = $o->getSortOrder ();

$field = $area = $file = $dropDown = $radio = $checkbox = $multiple = $date = $dateTime = $time = '';

/**
 * option type as dropdown.
 */
$optionTypeData == 'drop_down' ? $dropDown = 'selected' : '';
/**
 * option type as date time.
 */
$optionTypeData == 'date_time' ? $dateTime = 'selected' : '';

/**
 * Check option type is equal to drop down
 * or option type is equal to radio
 * or option type is equal to checkbox
 * or option type is equal to multiple
 * Get the values
 */
if ($optionTypeData == 'date' || $optionTypeData == 'date_time' || $optionTypeData == 'time') {
    $optionPrice = $optionPriceTypeData = $optionSkuVar = '';
    $optionPrice = round ( $o->getPrice (), 2 );
    $optionPriceTypeData = $o->getPriceType ();
    $optionSkuVar = $o->getSku ();
    $childOptionCountValue = $child_option_count_value;
    ?>
<table class="border form-list" cellpadding="0" cellspacing="0">
 <tbody>
  <tr class="headings">
   <th class="type-price"><label><?php echo $this->__('Price'); ?></label></th>
   <th class="type-type"><label><?php echo $this->__('Price Type'); ?></label></th>
   <th class="last"><label><?php echo $this->__('SKU'); ?></label></th>
  </tr>
  <tr>
   <td><input type="text" class="input-text validate-number product-option-price"
    id="<?php echo 'product_option_' . $childOptionCountValue . '_price'; ?>"
    name="<?php
    echo 'product[options][' . $childOptionCountValue . '][price]';
    ?>"
    value="<?php
    echo $optionPrice;
    ?>"></td>
   <td>
<?php
    $percentString = $fixedString = '';
    if (isset ( $optionPriceTypeData ) && $optionPriceTypeData == 'percent') {
        $percentString = 'selected';
    }
    if (isset ( $optionPriceTypeData ) && $optionPriceTypeData == 'fixed') {
        $fixedString = 'selected';
    }
    ?>
<select name="<?php echo 'product[options][' . $childOptionCountValue . '][price_type]'; ?>"
    id="<?php
    echo 'product_option_' . $childOptionCountValue . '_price_type';
    ?>"
    class="select product-option-price-type" title="">
     <option value="fixed" <?php echo $fixedString; ?>>
<?php echo $this->__('fixed'); ?></option>
     <option value="percent" <?php echo $percentString; ?>>
<?php echo $this->__('Percent'); ?></option>
   </select>
   </td>
   <td class="last"><input type="text" class="input-text type-sku"
    name="<?php echo 'product[options][' . $childOptionCountValue . '][sku]'; ?>"
    value="<?php
    echo $optionSkuVar;
    ?>"></td>
  </tr>
 </tbody>
</table>
<?php
    $child_option_count_value = $childOptionCountValue;
    $child_option_count_value = $child_option_count_value + 1;
}
$option_count = $option_count + 1;
?>