<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.9.2
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<?php
/**
 * Getting order data
 */
$data = $this->getData();
$currencySymbol = Mage::app ()->getLocale ()->currency ( Mage::app ()->getStore ()->getCurrentCurrencyCode () )->getSymbol ();
/**
 * Getting seller profile information
 */
                $sellerProfile = $this->getSellerProfile($data ['seller_id']);
                $sellerDefaultCountry = $sellerProfile['country'];
                $nationalShippingPrice = $sellerProfile['national_shipping_cost'];
                $totalProductAmt = $totalCommissionFee = $totalSellerAmt = 0;
                $internationalShippingPrice = $sellerProfile['international_shipping_cost'];
                $sellerId = $data ['seller_id'];
                $groupId = $this->getSellerGroupId();
                $productId = $data ['product_id'];
                $product = $this->getProductInfo ( $productId );
                $productGroupId = $product->getGroupId ();
                $productTypeId=$product->getTypeId();
                $productName = $product->getName ();
                /**
                 * Calculating seller amount based on seller shipping country
                 */
                $typeIdArray=array("virtual","downloadable");
                if ($sellerDefaultCountry == $shippingId && $nationalShippingPrice != ''&&(!(in_array($productTypeId,$typeIdArray)))){
                $nationalShippingPrice = $nationalShippingPrice * $data ['product_qty'];
                $SellerShppingCost = $data ['seller_amount']-$data['commission_fee'] + $nationalShippingPrice; ?>
                <td align="center" valign="top" style="font-size:11px;padding:3px 9px;border-bottom:1px dotted #cccccc;"><?php echo $currencySymbol . round ( $SellerShppingCost, 2 ); ?></td>
                <?php }
                else if ($sellerDefaultCountry != $shippingId && $internationalShippingPrice != ''&&(!(in_array($productTypeId,$typeIdArray)))){
                $internationalShippingPrice = $internationalShippingPrice * $data ['product_qty'];
                $SellerShppingCost = $data ['seller_amount']-$data['commission_fee']  + $internationalShippingPrice; ?>
                <td align="center" valign="top" style="font-size:11px;padding:3px 9px;border-bottom:1px dotted #cccccc;"><?php echo $currencySymbol . round ( $SellerShppingCost, 2 );?></td>
                <?php } else { ?>
                <td align="center" valign="top" style="font-size:11px;padding:3px 9px;border-bottom:1px dotted #cccccc;"><?php echo $currencySymbol . round ( $data ['seller_amount']-$data['commission_fee'] , 2 );?></td>
                <?php } ?>
